# Travis-CI Build for ConfigurationParser
# see travis-ci.org for details

language: csharp
sudo: required
solution: ConfigurationParser.sln

before_install:
  - export EnableNuGetPackageRestore=true

# Make sure build dependencies are installed.
install:
 - sudo apt-get install -y gtk-sharp2
 #- travis_retry nuget install .nuget/packages.config -SolutionDirectory packages
 - travis_retry nuget restore ConfigurationParser.sln -Verbosity detailed
 - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
 
#cache: 
# - apt
# - directories:
#   - packages

# Run the build script
script:
 - xbuild /p:Configuration=Release ConfigurationParser.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ConfigurationParserTests/bin/Release/ConfigurationParserTests.dll

# Only watch the master branch.
branches:
 only:
   - master
